// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBwpemdC_KgU_6v990oMDQwSj7HWarsgqc',
    appId: '1:954091064836:web:a42fbbc10ac7086ef62f51',
    messagingSenderId: '954091064836',
    projectId: 'items-demo-243c0',
    authDomain: 'items-demo-243c0.firebaseapp.com',
    storageBucket: 'items-demo-243c0.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDJtTkDuYbNE7TIjUwFul6-nbxg03Uwcqs',
    appId: '1:954091064836:android:da0310425fd342b5f62f51',
    messagingSenderId: '954091064836',
    projectId: 'items-demo-243c0',
    storageBucket: 'items-demo-243c0.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBwpemdC_KgU_6v990oMDQwSj7HWarsgqc',
    appId: '1:954091064836:web:60bdf6c32fc3427cf62f51',
    messagingSenderId: '954091064836',
    projectId: 'items-demo-243c0',
    authDomain: 'items-demo-243c0.firebaseapp.com',
    storageBucket: 'items-demo-243c0.firebasestorage.app',
  );
}
