// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDiVdtGsSFVPLXqCw9_aK20h7nAekE-Q58',
    appId: '1:287766812385:web:131786506a0dd0f9dd89a0',
    messagingSenderId: '287766812385',
    projectId: 'fir-lecture-8a3a6',
    authDomain: 'fir-lecture-8a3a6.firebaseapp.com',
    storageBucket: 'fir-lecture-8a3a6.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCk7zWgZU3NFxpokC0LRDhBKdpSraFYcPU',
    appId: '1:287766812385:android:dca44731eb33adebdd89a0',
    messagingSenderId: '287766812385',
    projectId: 'fir-lecture-8a3a6',
    storageBucket: 'fir-lecture-8a3a6.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDiVdtGsSFVPLXqCw9_aK20h7nAekE-Q58',
    appId: '1:287766812385:web:776b1a91694a3e43dd89a0',
    messagingSenderId: '287766812385',
    projectId: 'fir-lecture-8a3a6',
    authDomain: 'fir-lecture-8a3a6.firebaseapp.com',
    storageBucket: 'fir-lecture-8a3a6.firebasestorage.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA9aHfnnYJhueecOtjebdYinWV-LMko2XI',
    appId: '1:287766812385:ios:a9b8d4c2074b7b6edd89a0',
    messagingSenderId: '287766812385',
    projectId: 'fir-lecture-8a3a6',
    storageBucket: 'fir-lecture-8a3a6.firebasestorage.app',
    iosBundleId: 'com.example.adminApp',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA9aHfnnYJhueecOtjebdYinWV-LMko2XI',
    appId: '1:287766812385:ios:a9b8d4c2074b7b6edd89a0',
    messagingSenderId: '287766812385',
    projectId: 'fir-lecture-8a3a6',
    storageBucket: 'fir-lecture-8a3a6.firebasestorage.app',
    iosBundleId: 'com.example.adminApp',
  );

}